package co.gov.dane.uo.modelo;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ApiAmortizacion generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "usuario", catalog = "danetest")
public class Usuario implements java.io.Serializable {

	private Integer id;
	private String nombres;
	private String apellidos;
	private String direccion;
	private String celular;
	private String fechaNacimiento;
	private Set<Rol> rol = new HashSet<Rol>(0);

	public Usuario() {
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nombres", nullable = false, length = 10)
	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	@Column(name = "direccion", nullable = false, length = 100)
	public String getDireccion() {
		return direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "celular", nullable = false, length = 20)
	public String getCelular() {
		return celular;
	}

	public void setCelular(String celular) {
		this.celular = celular;
	}

	@Column(name = "fechaNac", nullable = false, length = 10)
	public String getFechaNacimiento() {
		return fechaNacimiento;
	}

	public void setFechaNacimiento(String fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	@Column(name = "apellidos", nullable = false, length = 100)
	public String getApellidos() {
		return apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "roleId")
	public Set<Rol> getApiUtilidadPrestamoses() {
		return this.rol;
	}

	public void setApiUtilidadPrestamoses(Set<Rol> rol) {
		this.rol = rol;
	}

}
